# define cd lc-hook: files, permissions, scripts
version: 0.0
os: linux
files:
  - source: /
    destination: /airflow
hooks:
  # similar to entrypoint.sh
  ApplicationStart:
    - location: scripts/cdapp_start.sh
      runas: root
  ApplicationStop:
    - location: scripts/cdapp_stop.sh
      runas: root
  # BeforeInstall:
  #   - location: scripts/install_dependencies.sh
  #     timeout: 300
  #     runas: root
  # AfterInstall:
  #   - location: scripts/change_permissions.sh
  #     timeout: 300
  #     runas: root